"""create_all_tables

Revision ID: 2f9bb2349bb9
Revises: 
Create Date: 2026-03-15 13:27:40.801439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9bb2349bb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('user_type', sa.Enum('citizen', 'broker', 'govt', name='user_type_enum'), nullable=True),
    sa.Column('subscription_plan', sa.Enum('free', 'basic', 'premium', name='subscription_plan_enum'), nullable=True),
    sa.Column('subscription_expires', sa.DateTime(), nullable=True),
    sa.Column('total_submissions', sa.Integer(), nullable=True),
    sa.Column('total_vault_items', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)

    op.create_table('submissions',
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('document_file_path', sa.String(length=500), nullable=True),
    sa.Column('village_name', sa.String(length=200), nullable=True),
    sa.Column('plot_number', sa.String(length=100), nullable=True),
    sa.Column('seller_name', sa.String(length=200), nullable=True),
    sa.Column('buyer_tribal', sa.Boolean(), nullable=True),
    sa.Column('submission_status', sa.Enum('processing', 'completed', 'failed', name='submission_status_enum'), nullable=True),
    sa.Column('pipeline_step', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Enum('GREEN', 'YELLOW', 'ORANGE', 'RED', name='risk_level_enum'), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'failed', 'demo_skip', name='payment_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_user_id'), ['user_id'], unique=False)

    op.create_table('khatiyan_extractions',
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('ocr_engine_used', sa.String(length=50), nullable=True),
    sa.Column('plot_number_extracted', sa.String(length=100), nullable=True),
    sa.Column('plot_confidence', sa.Float(), nullable=True),
    sa.Column('khata_number_extracted', sa.String(length=100), nullable=True),
    sa.Column('area_bigha_extracted', sa.Float(), nullable=True),
    sa.Column('owner_name_extracted', sa.String(length=200), nullable=True),
    sa.Column('tribal_status_extracted', sa.String(length=10), nullable=True),
    sa.Column('last_mutation_date_extracted', sa.String(length=20), nullable=True),
    sa.Column('overall_extraction_confidence', sa.Float(), nullable=True),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.PrimaryKeyConstraint('extraction_id')
    )
    with op.batch_alter_table('khatiyan_extractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_khatiyan_extractions_submission_id'), ['submission_id'], unique=False)

    op.create_table('payment_history',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=True),
    sa.Column('payment_type', sa.Enum('one_time', 'subscription', name='payment_type_enum'), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='payment_status_history_enum'), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    with op.batch_alter_table('payment_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_history_user_id'), ['user_id'], unique=False)

    op.create_table('risk_assessment',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('ocr_confidence_score', sa.Integer(), nullable=True),
    sa.Column('tribal_status_score', sa.Integer(), nullable=True),
    sa.Column('dc_permission_score', sa.Integer(), nullable=True),
    sa.Column('forest_risk_score', sa.Integer(), nullable=True),
    sa.Column('mutation_history_score', sa.Integer(), nullable=True),
    sa.Column('khatiyan_age_score', sa.Integer(), nullable=True),
    sa.Column('chain_of_title_score', sa.Integer(), nullable=True),
    sa.Column('final_risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Enum('GREEN', 'YELLOW', 'ORANGE', 'RED', name='risk_level_assessment_enum'), nullable=True),
    sa.Column('recommendation', sa.Enum('APPROVE', 'REVIEW', 'REJECT', name='recommendation_enum'), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    with op.batch_alter_table('risk_assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessment_submission_id'), ['submission_id'], unique=False)

    op.create_table('user_vault',
    sa.Column('vault_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=True),
    sa.Column('vault_name', sa.String(length=200), nullable=True),
    sa.Column('plot_number', sa.String(length=100), nullable=True),
    sa.Column('village_name', sa.String(length=200), nullable=True),
    sa.Column('area_bigha', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('GREEN', 'YELLOW', 'ORANGE', 'RED', name='risk_level_vault_enum'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('share_permission', sa.Enum('private', 'family', 'public', name='share_permission_enum'), nullable=True),
    sa.Column('family_members', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vault_id')
    )
    with op.batch_alter_table('user_vault', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_vault_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_vault', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_vault_user_id'))

    op.drop_table('user_vault')
    with op.batch_alter_table('risk_assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessment_submission_id'))

    op.drop_table('risk_assessment')
    with op.batch_alter_table('payment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_history_user_id'))

    op.drop_table('payment_history')
    with op.batch_alter_table('khatiyan_extractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_khatiyan_extractions_submission_id'))

    op.drop_table('khatiyan_extractions')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_user_id'))

    op.drop_table('submissions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))

    op.drop_table('users')
    # ### end Alembic commands ###
