"""add_extraction_confidence_columns

Revision ID: e6ec1e40da17
Revises: 2f9bb2349bb9
Create Date: 2026-03-15 15:03:42.850242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ec1e40da17'
down_revision: Union[str, None] = '2f9bb2349bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('khatiyan_extractions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('khata_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('area_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('owner_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tribal_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mutation_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('village_name_extracted', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('extraction_language', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('khatiyan_extractions', schema=None) as batch_op:
        batch_op.drop_column('extraction_language')
        batch_op.drop_column('village_name_extracted')
        batch_op.drop_column('mutation_confidence')
        batch_op.drop_column('tribal_confidence')
        batch_op.drop_column('owner_confidence')
        batch_op.drop_column('area_confidence')
        batch_op.drop_column('khata_confidence')

    # ### end Alembic commands ###
